name: crawl

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --quiet --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Crawl
        run: php bin/app.php

      - name: Country ID
        run: php bin/cid.php

      - name: Zone
        run: php bin/zone.php

      - name: Count changes
        id: changes
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update Service availability
          delete-branch: true
          title: Update Service availability
          body: |
            Update Japan Post's International Mail Service availability.

            - Japanese: https://www.post.japanpost.jp/int/information/overview.html
            - English: https://www.post.japanpost.jp/int/information/overview_en.html
            - Chinese: https://www.post.japanpost.jp/int/information/overview_cn.html
        if: steps.changes.outcome == 'failure'
